name: "n8n Home Assistant"
description: "n8n-Home-Assistant"
version: "3.1.0"
slug: "n8n"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5678/tcp: 5678